# -*- coding: utf-8 -*-
"""Diwali_Sales_Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L4bvEp-qCbTPa7_zwTpfX9zJrBkOA267
"""

!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install seaborn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt # visualizing data
import matplotlib_inline
import seaborn as sns

df = pd.read_csv('/content/Diwali Sales Data.csv', encoding= 'unicode_escape')
df.shape

df.shape

df.head(10)

df.tail(10)

df.info()

df.drop(['Status','unnamed1'],axis=1,implace=true)

df.info()

pd.isnull(df)

pd.isnull(df).sum()

df.shape

df.dropna(inplace=True)

df.shape

pd.isnull(df).sum()

df['Amount'] = df['Amount'].astype('int')

df['Amount'].dtypes

df.columns

df.describe()

df[['Age','Orders', 'Amount']].describe()

"""## Exploratory Data Analysis

**Gender**
"""

df.columns

ax = sns.countplot(x='Gender', data=df)

ax = sns.countplot(x='Gender', data=df)

for bars in ax.containers:
    ax.bar_label(bars)

df.groupby(['Gender'], as_index=False)['Amount'].sum().sort_values(by='Amount', ascending=False)

sales_gen = df.groupby(['Gender'], as_index=False)['Amount'].sum().sort_values(by='Amount', ascending=False)
sns.barplot(x='Gender',y='Amount', data=sales_gen)

"""**From above graphs we can see that most of the buyers are females and even the purchasing power of females are greater than men**

**Age**
"""

ax = sns.countplot(x='Age Group', hue= 'Gender', data=df)

ax = sns.countplot(x='Age Group', hue= 'Gender', data=df)

for bars in ax.containers:
    ax.bar_label(bars)

sales_age = df.groupby(['Age Group'], as_index=False)['Amount'].sum().sort_values(by='Amount', ascending=False)
sns.barplot(x='Age Group',y='Amount', data=sales_age)

"""**From above graphs we can see that most of the buyers are of age group between 26-35 yrs female**

**State**
"""

df.columns

sales_states= df.groupby(['State'], as_index=False)['Amount'].sum().sort_values(by='Amount', ascending=False).head(5)
sns.set(rc={'figure.figsize':(17,5)})
sns.barplot(x='State',y='Amount', data=sales_states)

"""**From the above graphs we can see that most of the orders and sales are from UP and Maharashtra and karnataka respectively.**

**Marital Status**
"""

df.columns

ax = sns.countplot(x='Marital_Status', data=df)

for bars in ax.containers:
    ax.bar_label(bars)

sales_states= df.groupby(['Marital_Status','Gender'], as_index=False)['Amount'].sum().sort_values(by='Amount', ascending=False)
sns.set(rc={'figure.figsize':(6,5)})
sns.barplot(data= sales_states, x='Marital_Status',y='Amount', hue='Gender')

"""**From the above graphs we can see that most of the buyers are marrried(womens) and they have high purchasing power **

**Occupations**
"""

df.columns

sns.set(rc={'figure.figsize':(20,5)})
ax = sns.countplot(x='Occupation', data=df)

for bars in ax.containers:
    ax.bar_label(bars)

sales_states= df.groupby(['Occupation'], as_index=False)['Amount'].sum().sort_values(by='Amount', ascending=False).head(5)
sns.set(rc={'figure.figsize':(6,5)})
sns.barplot(data= sales_states, x= 'Occupation',y='Amount')

"""**From the above graphs we can see that most of the buyers are working in IT sector, Healtcare and Aviation**

**Product Category**
"""

df.columns

sns.set(rc={'figure.figsize':(30,5)})
ax = sns.countplot(x='Product_Category', data=df)

for bars in ax.containers:
    ax.bar_label(bars)

sales_states= df.groupby(['Product_Category'], as_index=False)['Amount'].sum().sort_values(by='Amount', ascending=False).head(5)
sns.set(rc={'figure.figsize':(15,5)})
sns.barplot(data= sales_states, x= 'Product_Category',y='Amount')

"""**From the above graph we can see that most of the sold products are from food, clothing and electronics category**

**Product ID**
"""

df.columns

sales_states= df.groupby(['Product_ID'], as_index=False)['Orders'].sum().sort_values(by='Orders', ascending=False).head(5)
sns.set(rc={'figure.figsize':(10,5)})
sns.barplot(data= sales_states, x= 'Product_ID',y='Orders')

#top 5 sold products

fig1, ax1 = plt.subplots(figsize=(12,7))
df.groupby('Product_ID')['Orders'].sum().nlargest(5).sort_values(ascending=False).plot(kind='bar')

"""Conclusion:


Married women age group 26-35 years from UP, Maharashtra and Karnataka working in IT sector, healtcare and aviation are more likely to buy products from Food, Footwear and electronics category
"""

